ROW_NUMBER_PROPERTY = "__row_number__"

STARTS_PROPERTY = "starts"
ENDS_PROPERTY = "ends"
STARTS2_PROPERTY = "starts_2"
ENDS2_PROPERTY = "ends_2"

STARTS_2IN1_PROPERTY = "starts_2in1"
ENDS_2IN1_PROPERTY = "ends_2in1"
STARTS_1IN2_PROPERTY = "starts_1in2"
ENDS_1IN2_PROPERTY = "ends_1in2"
MASK_1IN2_PROPERTY = "mask_1in2"
MASK_2IN1_PROPERTY = "mask_2in1"
LENGTHS_2IN1_PROPERTY = "lengths_2in1"
LENGTHS_1IN2_PROPERTY = "lengths_1in2"

DUMMY_SUFFIX_PROPERTY = "_right__"
DISTANCE_COL_PROPERTY = "__distance__"

LEFT_DIRECTION_PROPERTY = "left"
RIGHT_DIRECTION_PROPERTY = "right"

LEFT_SIDE_PROPERTY = "left"
RIGHT_SIDE_PROPERTY = "right"

CLOSEST_START_IDX_PROPERTY = "start_closest_idx"
CLOSEST_END_IDX_PROPERTY = "end_closest_idx"

ARANGE_COL_PROPERTY = "__arange__"
COUNT_PROPERTY = "__count__"
